service: dynamodb-lambda

frameworkVersion: '2'

custom:
  userTableName: 'users-table-${self:provider.stage}'
  uniqueTableName: 'uniques-table-${self:provider.stage}'

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: dev
  region: ap-southeast-2
  environment:
    USERS_TABLE: ${self:custom.userTableName}
    UNIQUES_TABLE: ${self:custom.uniqueTableName}
  iam:
    role:
      statements:
        - Effect: Allow
          Action:
            - dynamodb:Query
            - dynamodb:Scan
            - dynamodb:GetItem
            - dynamodb:PutItem
            - dynamodb:UpdateItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
          Condition:
            ForAllValues:StringNotLike:
              dynamodb:Attributes:
                - credentials
        - Effect: Allow
          Action:
            - dynamodb:UpdateItem
            - dynamodb:PutItem
          Resource:
            - Fn::GetAtt: [UsersTable, Arn]
          Condition:
            ForAllValues:StringEquals:
              dynamodb:Attributes:
                - credentials

functions:
  create:
    handler: functions/users-create.handler
    events:
      - http:
          path: users
          method: post
          cors: true

  list:
    handler: functions/users-list.handler
    events:
      - http:
          path: users
          method: get
          cors: true

resources:
  Resources:
    UsersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: id
            AttributeType: S
        KeySchema:
          - AttributeName: id
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.userTableName}
    UniquesTable:
      Type: AWS::DynamoDB::Table
      Properties:
        AttributeDefinitions:
          - AttributeName: value
            AttributeType: S
        KeySchema:
          - AttributeName: value
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
        TableName: ${self:custom.uniqueTableName}
